version: "3.7"
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    command: "server /data --console-address :9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 user password;
      /usr/bin/mc mb --ignore-existing myminio/bucket --region=ap-northeast-1;
      /usr/bin/mc policy set public myminio/bucket;
      exit 0;
      "

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    working_dir: /myapp/backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - ./vendor/bundle:/myapp/backend/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - ./settings/backend.env

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "8000:3000"
    stdin_open: true
    tty: true
    env_file:
      - ./settings/frontend.env

  bot:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    volumes:
      - ./bot:/usr/src/app
    env_file:
      - ./settings/bot.env
    ports:
      - "9090:9090"
    command: ["python", "main.py"]

volumes:
  pgdata:

