tunnel: b8a01cef-9264-4130-9ec4-8df4d9a8934a
credentials-file: /home/nonroot/.cloudflared/b8a01cef-9264-4130-9ec4-8df4d9a8934a.json
protocol: http2

ingress:
  - hostname: slack-message-finder.coconutml.com
    service: http://frontend:8000
  - hostname: slack-message-finder-api.coconutml.com
    service: http://api:3000
  - hostname: slack-message-finder-bot.coconutml.com
    service: http://bot:9000
  - hostname: slack-message-finder-db.coconutml.com
    service: http://db:5432
  - service: http_status:404
